plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.8'
    id 'io.spring.dependency-management' version '1.1.7'
}
ext {
    springCloudGcpVersion = "7.4.1"
}

group = 'com.teamEXP'
version = '0.0.1-SNAPSHOT'
description = 'learnflow-api'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // JWT 관련 패키지 추가
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    implementation 'com.google.cloud:spring-cloud-gcp-starter-storage'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    // Spring Security 관련 패키지 추가
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'com.mysql:mysql-connector-j'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    // FFmpegFrameGrabber 추가
    implementation("org.bytedeco:javacv-platform:1.5.9")

    // [신규 추가] 1. 프로메테우스 연동 (지표 수집용)
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    // [신규 추가] 2. 집킨(Zipkin) 연동 (분산 트레이싱 - 요청 흐름 추적용)
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'

    // [신규 추가] 3. 로키(Loki) 연동 (로그 수집용)
    implementation 'com.github.loki4j:loki-logback-appender:1.4.1'
    // 테스트 시 사용할 인메모리 DB H2 추가
    runtimeOnly 'com.h2database:h2'

}
dependencyManagement {
    imports {
        mavenBom "com.google.cloud:spring-cloud-gcp-dependencies:$springCloudGcpVersion"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
